name: Deploy website
on:
  push:
    branches: [ "master", "new-site" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Run first jekyll build
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Install Tailwind dependencies
        run: npm install

      - name: Run tailwind
        run: npm run prod

      - name: Run second jekyll build
        run: jekyll build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: robinsonz.me
